// <auto-generated />
namespace TEDALS_Ver01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FromSAP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FromSAP));
        
        string IMigrationMetadata.Id
        {
            get { return "201511250937485_FromSAP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
